// Generates a random number b/w 1 and 100
let num = Math.floor((Math.random() * 100) + 1);   // Math.floor() function rounds down the decimal number to the nearest whole number (integer)
let chances = 0;          // Initial vaulue of chances taken to guess a number
let guess;              // Variable to store the number to be input from user to be guessed

console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win the game...\n");
guess = prompt("Enter a number between 1 and 100: ");
++chances;     // To increment the number of chances taken

do{
    guess = Number.parseInt(guess);

    if(guess > num){
        console.log("Number entered is greater");
        guess = prompt("Enter again!!");
        guess = Number.parseInt(guess);
        ++chances;    // To increment the number of chances taken
        continue;
    }

    else if(guess < num){
        console.log("Number entered is smaller");
        guess = prompt("Enter again!!");
        guess = Number.parseInt(guess);
        ++chances;     // To increment the number of chances taken
        continue;
    }
}
while(guess != num);    //break the loop if number entered is equal to the number generated

let score = 100 - (chances * 5);    //To store the score of your game

console.log(`Congratulatiions!!\n You guessed the right number ${num} in ${chances} chances.\nYour score is ${score}.`);
